INSERT INTO types (id, type, size, activity_level, groups) VALUES
	('1', 'Indonesian Street Dog', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('2', 'Indonesian Pomeranian', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('3', 'Indonesian Mastiff', 'Medium', 'Moderate', 'Working Group'),
	('4', 'Indonesian Bali Dog', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('5', 'Indonesian Dachshund', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('6', 'Indonesian Javanese Street Dog', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('7', 'Indonesian Balinese Street Dog', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('8', 'Indonesian Sumatran Hound', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('9', 'Golden Retriever', 'Large', 'High', 'Working Group'),
	('10', 'Poodle', 'Small', 'Moderate', 'Toy Group'),
	('11', 'Labrador Retriever', 'Large', 'High', 'Working Group'),
	('12', 'German Shepherd', 'Large', 'High', 'Working Group'),
	('13', 'Dachshund', 'Medium', 'Moderate', 'Hound Group'),
	('14', 'Beagle', 'Small', 'Moderate', 'Hound Group'),
	('15', 'Chihuahua', 'Small', 'Low', 'Toy Group'),
	('16', 'Shiba Inu', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('17', 'Bulldog', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('18', 'Shih Tzu', 'Small', 'Moderate', 'Non-Sporting Group'),
	('19', 'Pekingese', 'Small', 'Moderate', 'Non-Sporting Group'),
	('20', 'Rottweiler', 'Medium', 'Moderate', 'Working Group'),
	('21', 'Mastiff', 'Large', 'Moderate', 'Working Group'),
	('22', 'Terrier', 'Medium', 'Moderate', 'Terrier Group'),
	('23', 'Basset Hound', 'Medium', 'Moderate', 'Hound Group'),
	('24', 'Irish Wolfhound', 'Medium', 'Moderate', 'Hound Group'),
	('25', 'Dalmatian', 'Medium', 'High', 'Hound Group'),
	('26', 'Pomeranian', 'Small', 'Low', 'Toy Group'),
	('27', 'Great Dane', 'Large', 'Moderate', 'Working Group'),
	('28', 'Collie', 'Medium', 'Moderate', 'Herding Group'),
	('29', 'Cocker Spaniel', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('30', 'Shetland Sheepdog', 'Medium', 'High', 'Herding Group'),
	('31', 'Papillon', 'Small', 'High', 'Toy Group'),
	('32', 'Pug', 'Small', 'Moderate', 'Toy Group'),
	('33', 'Finnish Spitz', 'Small', 'Moderate', 'Herding Group'),
	('34', 'Husky', 'Medium', 'Moderate', 'Working Group'),
	('35', 'Samoyed', 'Medium', 'High', 'Working Group'),
	('36', 'Miniature Schnauzer', 'Medium', 'Moderate', 'Terrier Group'),
	('37', 'Yorkshire Terrier', 'Small', 'Low', 'Toy Group'),
	('38', 'Havanese', 'Small', 'Moderate', 'Toy Group'),
	('39', 'Akita', 'Medium', 'Moderate', 'Working Group'),
	('40', 'Bichon Frise', 'Small', 'Low', 'Non-Sporting Group'),
	('41', 'Boxer', 'Medium', 'High', 'Working Group'),
	('42', 'Maltese', 'Small', 'Low', 'Toy Group'),
	('43', 'Airedale Terrier', 'Small', 'Moderate', 'Terrier Group'),
	('44', 'Komondor', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('45', 'Cairn Terrier', 'Small', 'Moderate', 'Terrier Group'),
	('46', 'Corgi', 'Small', 'Moderate', 'Herding Group'),
	('47', 'Siberian Husky', 'Medium', 'High', 'Working Group'),
	('48', 'Doberman', 'Medium', 'High', 'Working Group'),
	('49', 'Vizsla', 'Medium', 'High', 'Working Group'),
	('50', 'Bullmastiff', 'Medium', 'Moderate', 'Working Group'),
	('51', 'Labradoodle', 'Medium', 'Moderate', 'Toy Group'),
	('52', 'Cavalier King Charles Spaniel', 'Medium', 'Low', 'Toy Group'),
	('53', 'Malamute', 'Large', 'Moderate', 'Working Group'),
	('54', 'Brussels Griffon', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('55', 'Saint Bernard', 'Large', 'Moderate', 'Working Group'),
	('56', 'Whippet', 'Medium', 'Moderate', 'Hound Group'),
	('57', 'Maltipoo', 'Medium', 'Moderate', 'Toy Group'),
	('58', 'Norwegian Elkhound', 'Medium', 'Moderate', 'Hound Group'),
	('59', 'Greyhound', 'Medium', 'Moderate', 'Hound Group'),
	('60', 'Beagle mix', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('61', 'French Bulldog', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('62', 'Eskimo Dog', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('63', 'Sheltie', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('64', 'Rhodesian Ridgeback', 'Medium', 'High', 'Hound Group'),
	('65', 'Jack Russell', 'Medium', 'High', 'Non-Sporting Group'),
	('66', 'Basenji', 'Medium', 'Moderate', 'Hound Group'),
	('67', 'Schnauzer', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('68', 'Alaskan Malamute', 'Medium', 'High', 'Working Group'),
	('69', 'Border Collie', 'Medium', 'High', 'Herding Group'),
	('70', 'Bernese Mountain Dog', 'Large', 'Moderate', 'Working Group'),
	('71', 'Lhasa Apso', 'Medium', 'Low', 'Non-Sporting Group'),
	('72', 'Weimaraner', 'Medium', 'High', 'Non-Sporting Group'),
	('73', 'Toy Fox Terrier', 'Small', 'Low', 'Toy Group'),
	('74', 'Old English Sheepdog', 'Medium', 'Moderate', 'Working Group'),
	('75', 'Australian Terrier', 'Medium', 'High', 'Terrier Group'),
	('76', 'Borzoi', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('77', 'English Mastiff', 'Large', 'Moderate', 'Working Group'),
	('78', 'Australian Shepherd', 'Medium', 'High', 'Herding Group'),
	('79', 'Italian Greyhound', 'Small', 'Low', 'Toy Group'),
	('80', 'Silky Terrier', 'Small', 'Low', 'Toy Group'),
	('81', 'Afghan Hound', 'Medium', 'Moderate', 'Hound Group'),
	('82', 'Collie mix', 'Medium', 'Moderate', 'Herding Group'),
	('83', 'Scottish Deerhound', 'Medium', 'Moderate', 'Hound Group'),
	('84', 'Doberman Pinscher', 'Medium', 'Moderate', 'Working Group'),
	('85', 'Portuguese Water Dog', 'Medium', 'Moderate', 'Working Group'),
	('86', 'Keeshond', 'Medium', 'Moderate', 'Working Group'),
	('87', 'Japanese Chin', 'Small', 'Low', 'Toy Group'),
	('88', 'Norwich Terrier', 'Small', 'Moderate', 'Terrier Group'),
	('89', 'Tibetan Terrier', 'Medium', 'Low', 'Terrier Group'),
	('90', 'Bloodhound', 'Medium', 'Moderate', 'Hound Group'),
	('91', 'Chinese Shar-Pei', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('92', 'Aussie mix', 'Medium', 'Moderate', 'Working Group'),
	('93', 'Rajapalayam', 'Medium', 'Moderate', 'Working Group'),
	('94', 'Bull Terrier', 'Medium', 'Moderate', 'Terrier Group'),
	('95', 'Bali Street Dog', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('96', 'Batak Shepherd', 'Medium', 'Moderate', 'Herding Group'),
	('97', 'Kintamani Dog', 'Medium', 'Moderate', 'Herding Group'),
	('98', 'Jack Russell Terrier', 'Medium', 'Moderate', 'Terrier Group'),
	('99', 'Chow Chow', 'Medium', 'Moderate', 'Non-Sporting Group'),
	('100', 'English Springer Spaniel', 'Medium', 'Moderate', 'Non-Sporting Group');